os: windows

language: go

before_install:
  - go get -t -v ./...
  - go vet ./...

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
